services:
  - type: web
    name: tour-expense-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: tpty-trip-a6a49355e844.json
